name: flutter_weather
description: A Flutter application for weather.

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  rxdart: ^0.16.0+2
  http: ^0.11.3+16

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

