name: flutter_weather
description: A Flutter application for weather.

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  rxdart: ^0.16.0+2
  http: ^0.11.3+16
  shared_preferences: ^0.4.2
  sqflite: ^0.11.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - icons/100.png
    - icons/100n.png
    - icons/101.png
    - icons/102.png
    - icons/103.png
    - icons/103n.png
    - icons/104.png
    - icons/104n.png
    - icons/200.png
    - icons/201.png
    - icons/202.png
    - icons/203.png
    - icons/204.png
    - icons/205.png
    - icons/206.png
    - icons/207.png
    - icons/208.png
    - icons/209.png
    - icons/210.png
    - icons/211.png
    - icons/212.png
    - icons/213.png
    - icons/300.png
    - icons/300n.png
    - icons/301.png
    - icons/301n.png
    - icons/302.png
    - icons/303.png
    - icons/304.png
    - icons/305.png
    - icons/306.png
    - icons/307.png
    - icons/309.png
    - icons/310.png
    - icons/311.png
    - icons/312.png
    - icons/313.png
    - icons/314.png
    - icons/315.png
    - icons/316.png
    - icons/317.png
    - icons/318.png
    - icons/399.png
    - icons/400.png
    - icons/401.png
    - icons/402.png
    - icons/403.png
    - icons/404.png
    - icons/405.png
    - icons/406.png
    - icons/406n.png
    - icons/407.png
    - icons/408.png
    - icons/409.png
    - icons/410.png
    - icons/499.png
    - icons/500.png
    - icons/501.png
    - icons/502.png
    - icons/503.png
    - icons/504.png
    - icons/507.png
    - icons/508.png
    - icons/509.png
    - icons/510.png
    - icons/511.png
    - icons/512.png
    - icons/513.png
    - icons/514.png
    - icons/515.png
    - icons/900.png
    - icons/901.png
    - icons/999.png

